GET http://localhost:3000/products.json

###
GET http://localhost:3000/products/2.json

###

POST http://localhost:3000/products
content-type: application/json

  {
    "input_name": "monitor", 
    "input_price": "120",  
    "input_description": "something that can show you more mistakes on coding",
    "supplier_id": 3,
    "quantity": 76
  }

###
  PATCH http://localhost:3000/products/1
  content-type: application/json

  {
    "input_name": "monitor", 
    "input_price": "120",  
    "input_description": "something that can show you more mistakes on coding",
    "supplier_id": 3,
    "quantity": 76
  }

###
  POST http://localhost:3000/users.json
  content-type: application/json

  {
    "name": "Harry",
    "email": "Maguire@gmail.com",
    "password": "password",
    "password_confirmation": "password"
  }

###
  POST http://localhost:3000/orders.json
  content-type: application/json

  {
    "user_id": "1",
    "product_id": "7",
    "quantity": "3",
    "subtotal": "750",
    "tax": "67.00",
    "total": "817.00"
  }


###
GET http://localhost:3000/orders/3.json


###
GET http://localhost:3000/orders.json


