GET http://localhost:3000/products

###
GET http://localhost:3000/products/3.json

###

POST http://localhost:3000/products
content-type: application/json

  {
    "input_name": "Phone",
    "input_price": "650",
    "input_image": "https://www.att.com/idpassets/sales/uf/deals/cell-phone-deals/839650-Animated-Multi-Tile-iPhone12-retina.png",
    "input_description": "you can call whoever you want"
  }

###
  PATCH http://localhost:3000/products/1
  content-type: application/json

  {
    "input_name": "conditioner",
    "input_price": "30",
    "input_image": "https://www.biolage.com/-/media/Project/Biolage/Biolagecom/Images/PDP/Primary-Images/Full-Density/884486233943_Biolage_Advanced_Full_Density_Conditioner_400ml_USA.jpg",
    "input_description": "Hopefully will make your hair soft"
  }